name             'prgs_client_upgrade_launcher'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'All Rights Reserved'
description      'Schedules a one-shot Chef Client upgrade via cron_d (Linux) or windows_task (Windows)'
version          '0.1.0'
chef_version     '>= 16.0'
